const {Person, Passenger, Crew} = require("./Person.js")
const Plane = require("./Planes.js")

describe.skip("Distinguishing between Passengers and Crew", ()=>{
    test("Matthew is an instance of Passenger, not a crew member", ()=>{
        const passenger1 = new Passenger("Matthew")
        expect(passenger1 instanceof Passenger).toBeTruthy()
        expect(passenger1 instanceof Crew).toBeFalsy()
        expect(passenger1 instanceof Person).toBeTruthy()
    })
    test("Passenger has name and bags property from Person", ()=>{
        const passenger1 = new Passenger("Matthew")
        expect(passenger1.name).toBe("Matthew")
        expect(passenger1).toHaveProperty("bags")
    })
    test("Passenger can call assistance and ask for a drink", ()=>{
        const passenger1 = new Passenger("Matthew")
        expect(passenger1.callAssistant()).toBe("Please can I have a drink")
    })
    test("Crew member can greet passenger", ()=>{
        const crew1 = new Crew("Sandra")
        expect(crew1.greetPassengers()).toBe("Have a nice flight!")
    })
    test("Crew member can greet passenger", ()=>{
        const crew1 = new Crew("Sandra")
        expect(crew1.greetPassengers()).toBe("Have a nice flight!")
    })
    test("Crew and passengers have boarded the plane", ()=>{
        const crew1 = new Crew("Sandra")
        const crew2 = new Crew("Susan")
        const passenger1 = new Passenger("Sarah")
        const passenger2 = new Passenger("Matthew")
        const jet2 = new Plane ("Jet2")
        jet2.boardPlane(passenger1)
        jet2.boardPlane(passenger2)
        jet2.boardPlane(crew1)
        jet2.boardPlane(crew2)
        expect(jet2.boardedPassengers.length).toBe(2)
        expect(jet2.boardedCrew.length).toBe(2)
    })
    test("1x passenger and 1x crew have left the plane", ()=>{
        const crew1 = new Crew("Sandra")
        const crew2 = new Crew("Susan")
        const passenger1 = new Passenger("Sarah")
        const passenger2 = new Passenger("Matthew")
        const jet2 = new Plane ("Jet2")
        jet2.boardPlane(passenger1)
        jet2.boardPlane(passenger2)
        jet2.boardPlane(crew1)
        jet2.boardPlane(crew2)
        jet2.leavePlane(passenger2)
        jet2.leavePlane(crew1)
        expect(jet2.boardedPassengers.length).toBe(1)
        expect(jet2.boardedCrew.length).toBe(1)
        console.log(jet2.boardedPassengers)
    })
})
